### ISSUE TITLE
Is there any plans for a new release?

### ISSUE THREAD

**Issue by dn-l** [streamingfast/solana-go#8]
Is this library abandoned?
I see some new commits but the last release was almost one year ago.
Module owner declaration is outdated:
```
❯ go get -u github.com/streamingfast/solana-go
go get: github.com/streamingfast/solana-go@none updating to
	github.com/streamingfast/solana-go@v0.2.0: parsing go.mod:
	module declares its path as: github.com/dfuse-io/solana-go
	        but was required as: github.com/streamingfast/solana-go
```

https://github.com/streamingfast/solana-go/blob/12dfaa0b1721e91688304bcf7bd9e2d57bc940eb/.goreleaser.yml#L18

**Comment by maoueh** [comment]
This is not abandoned but it's not actively develop for now since we have other priorities right now. We do still perform maintenance tasks on the repository. We had to rename due to some branding issues and indeed, it creates a small mess, will try to clean up as issues are found.

About releases, we are rather bad at making timely release and the best flow is to update up to `master` branch for now.

```
go get streamingfast/solana-go@master
```

I could tag a release if you really need one though. Tell me if you need one.

**Comment by dn-l** [comment]
@maoueh gotya! thanks
